#! /usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	-PAD- 
#

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩


bspc monitor -d I II III IV V

bspc config border_width         	2
bspc config window_gap           	6

bspc config split_ratio          	0.58
bspc config single_monocle 	 	false
bspc config focus_follows_pointer	false
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

#bspc config focus_border_color		"#BD93F9"
#bspc config normal_border_color		"#BD93F9"
#bspc config active_border_color		"#BD93F9"
#bspc config presel_feedback_color	"#BD93F9"



#polybar &
sxhkd &

#picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill $HOME/dotfiles-lab/assets/Wallpapers/chill_5.jpg &
#$HOME/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &
xset r rate 333 33
